src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $raisonSociale = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column(length: 100)]
    private ?string $adresse = null;

    #[ORM\Column(length: 20)]
    private ?string $cp = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    #[ORM\OneToMany(mappedBy: 'entreprise', targetEntity: Employe::class, orphanRemoval: true)]
    #[ORM\OrderBy(["nom" => "ASC"])]
    // trier les employé de l'entreprise dans l'ordre alphabétique
    private Collection $employes;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): static
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function getDateCreationFr(): ?string
    {
        return $this->dateCreation->format("d-m-Y");
    }

    // Pour afficher date | ne pas faire , on ne modifie pas le getter 
    // public function getDateCreation(): ?string
    // {
    //     return $this->dateCreation->format("d-m-Y");
    // }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): static
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    // adresse complète

    public function getAdresseComplète()
    {
        return $this->adresse." ".$this->cp." ".$this->ville;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): static
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): static
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    // Pour ne pas avoir à concaténer

    // public function __toString()
    // {
    //     return $this->raisonSociale. "(".$this->cp." ".$this->ville.")";
    // }

    public function __toString()
    {
        return $this->raisonSociale;
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('raisonSociale', TextType::class, [
                'attr' => [ 
                    'class' => 'form-control'
                ]
            ])
            ->add('dateCreation', DateType::class, [
                'widget' => 'single_text',
                'attr' => [ 
                    'class' => 'form-control',
                ]
            ])
            // widget 'single_text': présenté sous forme de champ texte simple dans le formulaire
            // 'class' => 'form-control': stylé avec la classe CSS 'form-control' (bootsrap) 
            
            ->add('adresse', TextType::class, [
                'attr' => [ 
                    'class' => 'form-control'
                ]
            ])
            ->add('cp', TextType::class, [
                'attr' => [ 
                    'class' => 'form-control'
                ]
            ])
            ->add('ville', TextType::class, [
                'attr' => [ 
                    'class' => 'form-control'
                ]
            ])
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

// Utiliser plutot Repository que EntityManagerInterface: EntityManagerInterface permettra autre chose.
class EntrepriseController extends AbstractController
{
    #[Route('/entreprise', name: 'app_entreprise')]
    // public function index(EntityManagerInterface $entityManager): Response
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {
        // $entreprises = $entityManager->getRepository(Entreprise::class)->findAll();
        // $entreprises = $entrepriseRepository->findAll();

        // SELECT * FROM entreprise ORDER BY raisonSociale

        // SELECT * FROM entreprise WHERE ville = 'Strasbourg' ORDER BY raisonSociale ASC
        // $entreprises = $entrepriseRepository->findBy(["ville" => "Strasbourg"], ["raisonSociale" => "ASC"]);


        $entreprises = $entrepriseRepository->findBy([], ["raisonSociale" => "ASC"]);
        return $this->render('entreprise/index.html.twig', [
            'entreprises' => $entreprises,
        ]);
    }

    // Dans entreprise la clé primaire est id. va permettre de nous faire travailler le params converter ( permet faire le lien avec l'objet qu'on souhaite ) 

    // params converter: outil sym , calsse symfony , récupère par déduction 



    #[Route('/entreprise/new', name: 'new_entreprise')]
    #[Route('/entreprise/{id}/edit', name: 'edit_entreprise')]
    public function new_edit(Entreprise $entreprise = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        if(!$entreprise) {
            $entreprise = new Entreprise();
        }

        $form = $this->createForm(EntrepriseType::class, $entreprise);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
 
            $entreprise = $form->getData();
            // prepare PDO
            $entityManager->persist($entreprise);
            // execute PDO
            $entityManager->flush();

            return $this->redirectToRoute('app_entreprise');
        }

        //  bloc soumssion

        return $this->render('entreprise/new.html.twig', [
            'formAddEntreprise' => $form,
            'edit' => $entreprise->getId()
        ]);

        // affiche formulaire d'ajout

        // 'edit' => $entreprise->getId() : si édit = vrai(true) éditer une entreprise, sinon ajouter une entreprise (pour titre h1)
    }

    // on crée une nouvelle entreprise
    // crée formulaire entreprise type
    // si formulaire souis et valide
    // on récupere donnée formulaire
    // prepare object qui est pret à etre inseré en bas de donnée
    //  flush : execute
    //  on redirect

    #[Route('/entreprise/{id}/delete', name: 'delete_entreprise')]
    public function delete_entreprise(Entreprise $entreprise, EntityManagerInterface $entityManager){

        $entityManager->remove($entreprise);
        $entityManager->flush();

        return $this->redirectToRoute('app_entreprise');

    }

    #[Route('/entreprise/{id}', name: 'show_entreprise')]
    public function show(Entreprise $entreprise): Response
    {
        return $this->render('entreprise/show.html.twig', [
            'entreprise' => $entreprise,
        ]);
    }
}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des entreprises{% endblock %}

{% block body %}

    <h1>Liste des entreprises</h1>

    <a href="{{ path('new_entreprise')}}" class="btn btn-success">Ajouter une entreprise</a><br>

    {% for entreprise in entreprises %}
        <a href="{{ path('show_entreprise', {'id': entreprise.id}) }}">{{ entreprise }}</a>
        <a class="btn btn-warning" href="{{ path('edit_entreprise', {'id': entreprise.id}) }}">Edit</a>
        <a class="btn btn-danger" href="{{ path('delete_entreprise', {'id': entreprise.id}) }}">Supprimer</a>
        <br>
    {% endfor %}

{% endblock %}


{# Concatener #}

{# <b>{{ entreprise.raisonSociale }}</b>{{' (' ~ entreprise.cp ~ ' ' ~ entreprise.ville ~ ')'}} <br> #}

templates/entreprise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if edit %}
        Editer une entreprise
    {% else %}
        Ajouter une entreprise  
    {% endif %}
{% endblock %}

{% block body %}
    {% if edit %}
        <h1>Editer une entreprise</h1>
    {% else %}
        <h1>Ajouter une entreprise</h1>
    {% endif %}
    

    {# {{ form(formAddEntreprise) }} #}

    {{ form_start(formAddEntreprise) }}
        {{ form_row(formAddEntreprise.raisonSociale)}}
        {{ form_row(formAddEntreprise.dateCreation)}}
        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddEntreprise.adresse)}}
            </div>
            <div class="col-sm">
                {{ form_row(formAddEntreprise.cp)}}
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddEntreprise.ville)}}
        </div>
        {{ form_row(formAddEntreprise.valider) }}

    {{ form_end(formAddEntreprise) }}
{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une entreprise{% endblock %}

{% block body %}
    <h1>Détail d'une entreprise</h1>

    <h2>{{ entreprise }}</h2>

    <p>
        Adresse : {{ entreprise.adresseComplète }} <br>

        {#  Avec méthode crée #}
        {# Date de création : {{ entreprise.dateCreationFr }} #}

        {# Depuis twig : filter , date #}
        Date de création : {{ entreprise.dateCreation | date("d.m.Y")}}
    </p>

    {# employes : collection employé d'entity #}

    <h3>Liste des salariés</h3>
    {% if entreprise.employes | length > 0 %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Employe</th>
            </tr>
        </thead>
        <tbody>
            
        {% for employe in entreprise.employes %}
            <tr>
                <td><a href="{{ path('show_employe', {'id':employe.id}) }}">{{ employe }}</a></td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    
    {% else %}
        <p>Aucun salarié dans cette entreprise</p>
    {% endif %}
    

{% endblock %}