src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateEmbauche = null;

    #[ORM\ManyToOne(inversedBy: 'employes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entreprise $entreprise = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $ville = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(?\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): static
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function __toString()
    {
        return $this->prenom." ".$this->nom;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    //  Méthode rajouté

    public function getAge(): ?string
    {
        $now = new \DateTime();
        $interval = $this->dateNaissance->diff($now);
        return $interval->format("%Y");
    }
}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => [ 
                    'class' => 'form-control',
                ]
            ])
            // Un tableau des arguments : arguments de ce champ là
            // attr: attributs sur input typetext
            // form-control : bootstrap
            ->add('prenom', TextType::class, [
                'attr' => [ 
                    'class' => 'form-control',
                ]
            ])
            ->add('dateNaissance', DateType::class, [
                'widget' => 'single_text',
                'attr' => [ 
                    'class' => 'form-control',
                ]
            ])
            ->add('dateEmbauche', DateType::class, [
                'widget' => 'single_text',
                'attr' => [ 
                    'class' => 'form-control',
                ]
            ])
            ->add('ville', TextType::class, [
                'required' => false,
                'attr' => [ 
                    'class' => 'form-control'
                ]
            ])
            ->add('entreprise', EntityType::class, [
                'class' => Entreprise::class,
                'attr' => [
                    'class' => 'form-control'
                ]
                
                ])
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
        ;
    }

    // 'choice_label' => 'raisonSociale' si ne renvoie pas l'information voulue

    // EntityType: nom élément , type champ et tableau d'argument
    //  'class' => Entreprise::class ( indique de quel type son mes objets à l'intérieur de ma liste)
    //  Ce que renvoie par défaut la liste vient du __toString

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use App\Form\EmployeType;
use App\Repository\EmployeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmployeController extends AbstractController
{
    #[Route('/employe', name: 'app_employe')]
    public function index(EmployeRepository $employeRepository): Response
    {

        // $employes = $employeRepository->findAll();
        
        // SELECT * FROM employe ORDER BY nom ASC
        $employes = $employeRepository->findBy([], ["nom" => "ASC"]);
        return $this->render('employe/index.html.twig', [
            'employes' => $employes,
        ]);
    }

    
    #[Route('/employe/new', name: 'new_employe')]
    #[Route('/employe/{id}/edit', name: 'edit_employe')]
    public function new_edit(Employe $employe = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        if(!$employe) {
          $employe = new Employe();  
        } 

        $form = $this->createForm(EmployeType::class, $employe);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
 
            $employe = $form->getData();
            // prepare PDO
            $entityManager->persist($employe);
            // execute PDO
            $entityManager->flush();

            return $this->redirectToRoute('app_employe');
        }

        //  bloc soumssion


        return $this->render('employe/new.html.twig', [
            'formAddEmploye' => $form,
            'edit' => $employe->getId()
        ]);
    }

    #[Route('/employe/{id}/delete', name: 'delete_employe')]
    public function delete_employe(Employe $employe, EntityManagerInterface $entityManager){

        $entityManager->remove($employe);
        $entityManager->flush();

        return $this->redirectToRoute('app_employe');

    }

    #[Route('/employe/{id}', name: 'show_employe')]
    public function show(Employe $employe): Response
    {
        return $this->render('employe/show.html.twig', [
            'employe' => $employe,
        ]);
    }
}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des employés{% endblock %}

{% block body %}

    <h1>Liste des employés</h1>

    <a href="{{ path('new_employe')}}" class="btn btn-success">Ajouter une employe</a><br>

    {% for employe in employes %}

        <a href="{{ path('show_employe', {'id':employe.id})}}">{{ employe }}</a> ({{ employe.entreprise.raisonSociale }})
        <a class="btn btn-warning" href="{{ path('edit_employe', {'id': employe.id}) }}">Edit</a>
        <a class="btn btn-danger" href="{{ path('delete_employe', {'id': employe.id}) }}">Supprimer</a>
        <br>
        {# employe.entreprise.raisonSociale | Chainage :  objet employe objet entreprise rataché et accède à la raison de l'entreprise de l'employé #}
    {% endfor %}

{% endblock %}

templates/employe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une employe{% endblock %}

{% block body %}
    <h1>Ajouter une employe</h1>

    {# {{ form(formAddEmploye) }} #}
    {# affiche formulaire sans pouvoir personnaliser chaque partie #}

    {{ form_start(formAddEmploye) }}
        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddEmploye.nom)}}
            </div>
            <div class="col-sm">
                {{ form_row(formAddEmploye.prenom)}}
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddEmploye.dateNaissance)}}
        </div>
            <div class="col-sm">
                {{ form_row(formAddEmploye.dateEmbauche)}}
        </div>
        {{ form_row(formAddEmploye.entreprise)}}
        {{ form_row(formAddEmploye.ville)}}
        {{ form_row(formAddEmploye.valider)}}
    
    {{ form_end(formAddEmploye) }}

{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une employé{% endblock %}

{% block body %}
    <h1>Détail d'une employé</h1>

    <h2>{{ employe }}</h2>

    <p>
        Entreprise : <a href="{{ path('show_entreprise', {'id':employe.entreprise.id})}}">{{ employe.entreprise }}</a> <br>
        Ville : {% if employe.ville %}
                    {{ employe.ville }} <br>
                {% else %}
                    Ville non renseignée <br>
                {% endif %}
        Date de naissance : {{ employe.dateNaissance | date("d.m.Y")}} <br>
        Age : {{ employe.age }} ans<br>
        Date d'embauche : {{ employe.dateEmbauche | date("d.m.Y")}}
    </p>

{% endblock %}